const returnsActionTypes = {
  AGGREGATE_BATCHES: 'AGGREGATE_BATCHES',
  TOGGLE_PROCESS_RETURN_DIALOG: 'TOGGLE_PROCESS_RETURN_DIALOG',
  TOGGLE_ITEM_RESELLABBLE: 'TOGGLE_ITEM_RESELLABBLE',
  SET_RETURN_REASON: 'SET_RETURN_REASON',
  TOGGLE_SELECTED_BATCH: 'TOGGLE_SELECTED_BATCH',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  SET_RETURN_STATE: 'SET_RETURN_STATE',
  SET_PRODUCT_NOTE: 'SET_PRODUCT_NOTE',
  SET_MAIN_RETURN_NOTE: 'SET_MAIN_RETURN_NOTE',
  SET_SALE_DETAILS: 'SET_SALE_DETAILS',
  SET_SALE_DETAIL_RETURN_QUANTITY: 'SET_SALE_DETAIL_RETURN_QUANTITY',
  DISCARD_RETURN: 'DISCARD_RETURN',
  HOLD_RETURN: 'HOLD_RETURN'
};

export default returnsActionTypes;
