const customers = {
  openDialog: false,
  openCustomerDetailsDialog: false,
  customersRefetch: '',
  firstName: '',
  lastName: '',
  email: '',
  id: '',
  primaryMobileNumber: '',
  secondaryMobileNumber: '',
  loyaltyMember: false,
  isLoading: false,
  nameHelper: '',
  emailHelper: '',
  mobileHelper: '',
  nameError: false,
  emailError: false,
  mobileError: false,
  address: '',
  region: '',
  city: 'Abuja',
  cityId: 6,
  cities: [],
  country: '',
  countryId: 0,
  emergencyContactName: '',
  emergencyContactEmail: '',
  emergencyContactNumber: '',
  isSelected: '',
  selectedCustomer: null,
  formError: false,
  serverError: false,
};

export default customers;
