const SellActionTypes = {
  SET_SELL_STATE: 'SET_SELL_STATE',
  SET_PREFERRED_PRODUCTS: 'SET_PREFERRED_PRODUCTS',
  UPDATE_PREFERRED_PRODUCTS: 'UPDATE_PREFERRED_PRODUCTS',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
  TOGGLE_SALE_BATCH_DIALOG: 'TOGGLE_SALE_BATCH_DIALOG',
  TOGGLE_BATCHES_FOR_CART: 'TOGGLE_BATCHES_FOR_CART',
  BATCH_INPUT_CHANGE: 'BATCH_INPUT_CHANGE',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  ADD_ITEM_NOTE: 'ADD_ITEM_NOTE',
  HOLD_SALE: 'HOLD_SALE',
  TOGGLE_SELL_FROM_OUT_OF_STOCK: 'TOGGLE_SELL_FROM_OUT_OF_STOCK',
};

export default SellActionTypes;
