const BatchTypes = {
  GET_ORDER_BATCH: 'GET_ORDER_BATCH',
  ADD_PRODUCT_BATCH: 'ADD_PRODUCT_BATCH',
  GET_PRODUCT_BATCH: 'GET_PRODUCT_BATCH',
  UPDATE_PRODUCT_BATCH: 'UPDATE_PRODUCT_BATCH',
  UPDATE_SINGLE_BATCH: 'UPDATE_SINGLE_BATCH',
  CLOSE_PRODUCT_BATCH: 'CLOSE_PRODUCT_BATCH',
  SET_BATCH_LENGTH: 'SET_BATCH_LENGTH'
};

export default BatchTypes;
